#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  7 13:47:54 2020

@author: pete
"""


path_img = '/home/face/scene2/'
tests = [f for f in os.listdir(path_img) if f.endswith(('.jpg', '.jpeg', '.png'))]